// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkIV7Ww9YiGoBuwxxJFhG5_RX-Z_sZoO4',
    appId: '1:498819383401:web:433a58fe8fb15cab1922f8',
    messagingSenderId: '498819383401',
    projectId: 'luma-v1-af463',
    authDomain: 'luma-v1-af463.firebaseapp.com',
    storageBucket: 'luma-v1-af463.firebasestorage.app',
    measurementId: 'G-80NL7YG3J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7rbbI5cVx2wTEiqRLaIZtFfh_Gcl6Ew',
    appId: '1:498819383401:android:16106502e08fa72a1922f8',
    messagingSenderId: '498819383401',
    projectId: 'luma-v1-af463',
    storageBucket: 'luma-v1-af463.firebasestorage.app',
  );
}
